spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      hibernate:

        type:
          descriptor:
            sql:
              BasicBinder: TRACE